### ISSUE TITLE
images.h

### ISSUE THREAD

**Issue by anthonyjclarke** [lspoplove/D-duino#1]
Wont compile, as looking for this file, where is it located?

/Volumes/Macintosh HD 2/Users/Documents/Arduino/D-duino-master/Arduino-examples/OLED/OLEDtest/OLEDtest.ino:41:20: fatal error: images.h: No such file or directory
 #include "images.h"
                    ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by lspoplove** [comment]
Dear Mr Anthony Clarke,
 
Have you setup this library correctly?
https://github.com/squix78/esp8266-oled-ssd1306 
Please unzip this library to your arduino library.
Then I think it will work.
 
 
 
Travis Lin
Make something amazing with you.
www.dong-sen.com
 
-----Original Message-----

**Comment by anthonyjclarke** [comment]
Thank you, yes, I had removed this old library..... was using the new v3.0 (which is much better)!
