### ISSUE TITLE
USB / Mac OSX Connection

### ISSUE THREAD

**Issue by anthonyjclarke** [lspoplove/D-duino#2]
Hi

I am using Mac, and can compile code ok with Arduino IDE 1.18.

I have installed USB Drivers from : http://www.silabs.com/products/mcu/pages/usbtouartbridgevcpdrivers.aspx#mac

But when I try to upload I get : 

Sketch uses 251513 bytes (24%) of program storage space. Maximum is 1044464 bytes.
Global variables use 32192 bytes (39%) of dynamic memory, leaving 49728 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

Any advice?

**Comment by lspoplove** [comment]
Hello.It seems there is some problem are using your serial port. Please check your serial port. Close other software which could use the same port.Do not connect other sensors when you upload codes.Then please try again


发自Naver邮箱应用软件-----Original Message-----

**Comment by anthonyjclarke** [comment]
I tried on windows, installed your drivers, the same.

The Serial Port must be working, becuase when I open Serial Window and hit reset I see this:

"Ai-Thinker Technology Co. Ltd.

ready"

**Comment by lspoplove** [comment]
Please let me have a look at your test code


发自Naver邮箱应用软件-----Original Message-----

**Comment by anthonyjclarke** [comment]
I am trying any sample Arduino code… like Blink…. etc

Nothing uploads, I get the same error…. after I try to upload, I hit reset on board to test serial port….

**Comment by lspoplove** [comment]
Dear Mr anthonyjclarke. Could you please capture the wrong message? 
What is your upload speed? Have you changed it to 115200?
I think the hardware is OK. There maybe something problem at software setting.

**Comment by anthonyjclarke** [comment]
Hi, Thanks for helping me...

I have no problems on all my 12E and Wemos boards....

I changed upload to 115200 to see if that would fix, it did not... same
problem on all speeds

Where di you want me to capture error message? the message from Arduino
1.18 upload is :

warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

**Comment by lspoplove** [comment]
OK.I will send you a new one.


发自Naver邮箱应用软件-----Original Message-----

**Comment by lspoplove** [comment]
Sorry for making you feel boring.
I will send you a new one tomorrow
 
Travis Lin
Make something amazing with you.
www.dong-sen.com
 
-----Original Message-----

**Comment by anthonyjclarke** [comment]
Thank you

**Comment by lspoplove** [comment]
Dear Mr Clarke,
Your ship number is RX391026153DE
 
Travis Lin
Make something amazing with you.
www.dong-sen.com
 
-----Original Message-----

**Comment by anthonyjclarke** [comment]
Just wanted to let you know, replacement arrived... I was able to connect and upload code!  Thanks very much.....  Old one definately broken!!

**Comment by Head** [comment]
Hi,

same problem here. Got the board today and all I see is the demo runnung. It also has an open WiFi.

When I press reset at Baud 74880 I get:
```

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x42
csum 0x42
~ld
⸮T
```

But nothing on any other baud, cannot send AT commands.
When I programm it all I get is:

```Der Sketch verwendet 222201 Bytes (21%) des Programmspeicherplatzes. Das Maximum sind 1044464 Bytes.
Globale Variablen verwenden 31576 Bytes (38%) des dynamischen Speichers, 50344 Bytes für lokale Variablen verbleiben. Das Maximum sind 81920 Bytes.
\Arduino15\packages\esp8266\tools\esptool\0.4.9/esptool.exe -vv -cd nodemcu -cb 115200 -cp COM5 -ca 0x00000 -cf \Local\Temp\arduino_build_380452/Blink.ino.bin 
esptool v0.4.9 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
	setting board to nodemcu
	setting baudrate from 115200 to 115200
	setting port from COM1 to COM5
	setting address from 0x00000000 to 0x00000000
	espcomm_upload_file
	espcomm_upload_mem
	setting serial port timeouts to 1000 ms
opening bootloader
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
resetting board
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
trying to connect
	flush start
	setting serial port timeouts to 1 ms
	setting serial port timeouts to 1000 ms
	flush complete
Beim Hochladen des Sketches ist ein Fehler aufgetreten
	espcomm_send_command: sending command header
	espcomm_send_command: sending command payload
	read 0, requested 1
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
```

**Comment by lspoplove** [comment]
Hello, Which board you are using?
The baud must be 115200
