### ISSUE TITLE
OLED

### ISSUE THREAD

**Issue by scargill** [lspoplove/D-duino#3]
I have the board and want to use it with my own software that supports I2c and the SSD1306 OLED... but my search function shows no I2c device..

is the OLED connected as I2c -  or SPI ???

**Comment by lspoplove** [comment]
OLED connect as IIC.
D1 connected with SDA
D2 connected with SCL.
 
Travis Lin
Make something amazing with you.
www.dong-sen.com
 
-----Original Message-----

**Comment by scargill** [comment]
Sorted – thank you – SDA and SCL were the opposite way around to the way Espressif use it… swapped them over – display lit up!!!

 

Lovely..

 

Pete.
